Added new assets and fixed UI
senali-d/SyncX pull request #1
Opened 2023-06-09 18:20 UTC by neel-ds

- Optimized UI/UX
- Added new assets
- Updated content

2023-06-09 20:29 UTC, senali-d commented on src/pages/index.jsx
> +                img="/syncX.png"
@neel-ds Instead repeat component again and again. It is better we can loop through a json array.

2023-06-09 20:41 UTC, senali-d requested changes
Recheck and fix the responsive issues as well.

2023-06-10 10:57 UTC, senali-d commented on src/components/navbar.jsx
> +                src="/syncX.png"
```suggestion
                src="/syncx.png"
```

2023-06-10 10:59 UTC, senali-d commented on src/pages/index.jsx
> +    img: "/syncX.png",
```suggestion
    img: "/syncx.png",
```

2023-06-10 13:40 UTC, neel-ds commented
- Fixed mobile view of NavBar
- Added new featured assets 
- Updated Home & About page

2023-06-10 19:12 UTC, merged